name: Master
on:
  push: C:\Users\okuda\PycharmProjects\automationTest\main.py
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running23!"


